# Generated by Django 4.2.6 on 2023-11-23 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTrackCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_trackCode', models.CharField(max_length=300)),
                ('date_group_created', models.DateTimeField()),
                ('group_track_code', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Группу Трек-кодов',
                'verbose_name_plural': 'Группы Трек-кодов',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Статус Заказа',
                'verbose_name_plural': 'Статусы Заказов',
            },
        ),
        migrations.CreateModel(
            name='TrackCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_code_name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_codes', to='cargo_app.grouptrackcodes')),
            ],
            options={
                'verbose_name': 'Код Заказа',
                'verbose_name_plural': 'Коды Заказов',
            },
        ),
        migrations.AddField(
            model_name='grouptrackcodes',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_statuses', to='cargo_app.status'),
        ),
    ]
