# Generated by Django 4.2.6 on 2023-10-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Статус Заказа',
                'verbose_name_plural': 'Статусы Заказов',
            },
        ),
        migrations.CreateModel(
            name='TrackCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_code', models.CharField(max_length=200, unique=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cargo_app.status')),
            ],
            options={
                'verbose_name': 'Код Заказа',
                'verbose_name_plural': 'Коды Заказов',
            },
        ),
    ]
