# Generated by Django 4.2.6 on 2023-11-25 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackcode',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='cargo_app.group'),
            preserve_default=False,
        ),
    ]
