# Generated by Django 4.2.6 on 2023-11-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0002_trackcode_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='track_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
