# Generated by Django 4.2.6 on 2023-11-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0002_grouptrackcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('statuses', models.ManyToManyField(blank=True, related_name='groups', to='cargo_app.status')),
                ('track_codes', models.ManyToManyField(blank=True, related_name='groups', to='cargo_app.trackcode')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.DeleteModel(
            name='GroupTrackCode',
        ),
    ]
