# Generated by Django 4.2.6 on 2023-10-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0002_alter_trackcode_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackcode',
            old_name='code',
            new_name='track_code',
        ),
    ]
