# Generated by Django 4.2.6 on 2023-11-25 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0003_group_track_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='track_code',
        ),
    ]
