# Generated by Django 4.2.6 on 2023-11-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0004_remove_group_name_remove_group_statuses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTrackCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_trackCode', models.CharField(max_length=300)),
                ('date_group_created', models.DateTimeField()),
                ('statuses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_statuses', to='cargo_app.status')),
            ],
            options={
                'verbose_name': 'Группу Трек-кодов',
                'verbose_name_plural': 'Группы Трек-кодов',
            },
        ),
        migrations.RenameField(
            model_name='trackcode',
            old_name='track_code',
            new_name='track_code_name',
        ),
        migrations.RemoveField(
            model_name='trackcode',
            name='date',
        ),
        migrations.RemoveField(
            model_name='trackcode',
            name='status',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='grouptrackcodes',
            name='track_codes',
            field=models.ManyToManyField(blank=True, related_name='groups_track_codes', to='cargo_app.trackcode'),
        ),
    ]
