# Generated by Django 4.2.6 on 2023-11-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0004_remove_group_name_remove_group_statuses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группу Трек-кодов', 'verbose_name_plural': 'Группы Трек-кодов'},
        ),
    ]
