# Generated by Django 4.2.6 on 2023-11-25 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0004_remove_group_track_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='track_codes',
        ),
        migrations.AddField(
            model_name='group',
            name='track_codes',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
