# Generated by Django 4.2.6 on 2023-11-25 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0005_remove_group_track_codes_group_track_codes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='track_codes',
        ),
    ]
