# Generated by Django 4.2.6 on 2023-11-22 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0005_grouptrackcodes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptrackcodes',
            name='track_codes',
        ),
        migrations.AddField(
            model_name='grouptrackcodes',
            name='track_codes',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups_track_codes', to='cargo_app.trackcode'),
            preserve_default=False,
        ),
    ]
