# Generated by Django 4.2.6 on 2023-11-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0005_alter_group_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='statuses',
            new_name='status',
        ),
    ]
