# Generated by Django 4.2.6 on 2023-11-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0006_remove_grouptrackcodes_track_codes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptrackcodes',
            name='track_codes',
        ),
        migrations.AddField(
            model_name='grouptrackcodes',
            name='track_codes',
            field=models.ManyToManyField(related_name='groups', to='cargo_app.trackcode'),
        ),
    ]
