# Generated by Django 4.2.6 on 2023-10-12 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description_status', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Статус Заказа',
                'verbose_name_plural': 'Статусы Заказов',
            },
        ),
        migrations.CreateModel(
            name='TrackCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=300, unique=True, verbose_name='Код для отслеживания статуса заказа')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cargo_app.status', verbose_name='Трек Код')),
            ],
            options={
                'verbose_name': 'Трек Код',
                'verbose_name_plural': 'Трек Коды',
            },
        ),
    ]
