# Generated by Django 4.2.6 on 2023-10-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=300, unique=True, verbose_name='Код для отслеживания статуса заказа')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Трек Код',
                'verbose_name_plural': 'Трек Коды',
            },
        ),
    ]
