# Generated by Django 4.2.6 on 2023-10-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='description_status',
        ),
    ]
