# Generated by Django 4.2.6 on 2023-10-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0002_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус Заказа', 'verbose_name_plural': 'Статусы Заказов'},
        ),
    ]
