# Generated by Django 4.2.6 on 2023-10-12 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0002_remove_status_description_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackcode',
            name='code',
            field=models.CharField(db_index=True, default='', max_length=300, unique=True, verbose_name='Код для отслеживания статуса заказа'),
        ),
        migrations.AlterField(
            model_name='trackcode',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cargo_app.status', verbose_name='статус'),
        ),
    ]
