# Generated by Django 4.2.6 on 2023-10-12 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo_app', '0003_alter_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='description_status',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='track_code',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='cargo_app.trackcode'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackcode',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
